version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./backup_db/kintolayli_db_backup.dump:/docker-entrypoint-initdb.d/kintolayli_db_backup.dump
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: kintolayli/postarama_docker-web
#    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
#    command: sh -c "python manage.py collectstatic --no-input &&
 #               python manage.py makemigrations &&
  #              python manage.py migrate &&
   #             gunicorn --workers=4 --reload --max-requests=1000 yatube.wsgi -b 0.0.0.0:8000""

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    depends_on:
      - nginx
#    command: certonly --webroot --webroot-path=/var/www/certbot/ --email golkiper-leo@yandex.ru --agree-tos --no-eff-email --stag>

volumes:
  static_value:
  media_value:
