# Generated by Django 2.2.6 on 2020-11-22 21:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_like'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('likes', django.db.models.manager.Manager()),
            ],
        ),
    ]
