# Generated by Django 2.2.6 on 2020-11-22 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_auto_20201123_0052"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
