# Generated by Django 2.2.6 on 2020-11-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_auto_20201123_0102"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-updated",)},
        ),
        migrations.AddField(
            model_name="comment",
            name="text2",
            field=models.TextField(default="", max_length=500),
        ),
    ]
