# Generated by Django 2.2.6 on 2020-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201123_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text2',
        ),
    ]
