# Generated by Django 2.2.6 on 2020-11-30 23:26

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("posts", "0010_auto_20201123_2018"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuTag",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taggit.tag",),
        ),
        migrations.CreateModel(
            name="RuTaggedItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taggit.taggeditem",),
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("updated",)},
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="posts.RuTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
