# Generated by Django 2.2.6 on 2020-12-01 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_auto_20201201_0226"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created",)},
        ),
    ]
