# Generated by Django 2.2.6 on 2020-12-12 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
